<?php

namespace Magenest\CustomEav\Ui\Listing\Column;

use Magento\Backend\Model\Auth\Session;
use Magento\Framework\View\Element\UiComponent\ContextInterface;
use Magento\Framework\View\Element\UiComponentFactory;
use Magento\Ui\Component\Listing\Columns\Column;

class DumpText extends Column{
    /**
     * @var Session
     */
    private $authSession;

    public function __construct(
        ContextInterface $context,
        UiComponentFactory $uiComponentFactory,
        Session $authSession,
        array $components = [],
        array $data = [])
    {
        parent::__construct($context, $uiComponentFactory, $components, $data);
        $this->authSession = $authSession;
    }
    public function prepare()
    {
        parent::prepare(); // TODO: Change the autogenerated stub
        $username = $this->authSession->getData('user')->getUserName();
        if ($username[0]>='A'&&$username[0]<='M'){
            $this->_data['config']['componentDisabled'] = false;
        }
    }
    public function prepareDataSource(array $dataSource)
    {
       return $dataSource;
    }
}